HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:cyq_SD1
Implementation;Synthesis||null||@N: Running in 64-bit mode||cyq_SD1.srr(11);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/11||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||cyq_SD1.srr(15);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/15||null;null
Implementation;Synthesis|| CG364 ||@N: Synthesizing module cyq_74HC153 in library work.||cyq_SD1.srr(28);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/28||cyq_comb.v(29);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\hdl\cyq_comb.v'/linenumber/29
Implementation;Synthesis|| CG364 ||@N: Synthesizing module cyq_SD1 in library work.||cyq_SD1.srr(30);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/30||cyq_SD1.v(9);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\component\work\cyq_SD1\cyq_SD1.v'/linenumber/9
Implementation;Synthesis||null||@N: Running in 64-bit mode||cyq_SD1.srr(42);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/42||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||cyq_SD1.srr(63);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/63||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||cyq_SD1.srr(86);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/86||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||cyq_SD1.srr(87);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/87||null;null
Implementation;Synthesis|| BN225 ||@N: Writing default property annotation file E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.sap.||cyq_SD1.srr(108);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/108||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||cyq_SD1.srr(135);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/135||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||cyq_SD1.srr(136);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/136||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||cyq_SD1.srr(241);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/241||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||cyq_SD1.srr(243);liberoaction://cross_probe/hdl/file/'E:\cyq\J3122008883_Comb\synthesis\cyq_SD1.srr'/linenumber/243||null;null
Implementation;Compile;RootName:cyq_SD1
Implementation;Compile||(null)||Please refer to the log file for details||cyq_SD1_compile_log.rpt;liberoaction://open_report/file/cyq_SD1_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:cyq_SD1
Implementation;Generate Bitstream;RootName:cyq_SD1
