<project name="cyq_SD1" version="1.1">
    <ProjectDirectory>
        D:\Study\LiberoProjects\Submit_20231228\Exp8_Test2\J3122008883_Comb\designer\impl1\cyq_SD1_fp
    </ProjectDirectory>
    <View>
        SingleSTAPLView
    </View>
    <LiberoTargetDevice>
        
    </LiberoTargetDevice>
    <LogFile>
        D:\Study\LiberoProjects\Submit_20231228\Exp8_Test2\J3122008883_Comb\designer\impl1\cyq_SD1_fp\cyq_SD1.log
    </LogFile>
    <SerializationOption>
        Skip
    </SerializationOption>
    <programmer status="enable" type="FlashPro5" revision="UndefRev" connection="usb2.0">
        <name>
            S2001L06UA
        </name>
        <id>
            S2001L06UA
        </id>
    </programmer>
    <configuration>
        <Hardware>
            <FlashPro>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
                <Vddl/>
                <Vdd>
2500                </Vdd>
            </FlashPro>
            <FlashProLite>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
            </FlashProLite>
            <FlashPro3>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro3>
            <FlashPro4>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro4>
            <FlashPro5>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
                <ProgrammingMode>
                    JTAGMode
                </ProgrammingMode>
            </FlashPro5>
        </Hardware>
        <Algo type="PDB">
            <filename>
                D:\Study\LiberoProjects\Submit_20231228\Exp8_Test2\J3122008883_Comb\designer\impl1\cyq_SD1.pdb
            </filename>
            <local>
                projectData\cyq_SD1.pdb
            </local>
            <SelectedAction>
                PROGRAM
            </SelectedAction>
        </Algo>
    </configuration>
</project>
