Implementation;Generate Bitstream;RootName:lly_fsm_0101
HelpInfo,D:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,D:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Compile;RootName:lly_VM
Implementation;Compile||(null)||Please refer to the log file for details||lly_VM_compile_log.rpt;liberoaction://open_report/file/lly_VM_compile_log.rpt||(null);(null)
Implementation;Place and Route||PLC007;liberoaction://open_online_help/89129363||Info: Created quadrant global region Qclock_Clk_c for global net Clk_c.||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:lly_VM
Implementation;Place and Route||(null)||Please refer to the log file for details about 2 Info(s)||lly_VM_placeroute_log.rpt;liberoaction://open_report/file/lly_VM_placeroute_log.rpt||(null);(null)
