Implementation;Generate Bitstream;RootName:cyq_74HC194
HelpInfo,D:\Libero Soc\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,D:\Libero Soc\SynplifyPro\bin\mbin\assistant
Implementation;Compile;RootName:cyq_SSD2
Implementation;Compile||(null)||Please refer to the log file for details about 1 Warning(s)||cyq_SSD2_compile_log.rpt;liberoaction://open_report/file/cyq_SSD2_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:cyq_SSD2
