Implementation;Compile;RootName:lly_SD1
Implementation;Compile||(null)||Please refer to the log file for details about 1 Warning(s)||lly_SD1_compile_log.rpt;liberoaction://open_report/file/lly_SD1_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:lly_SD1
Implementation;Place and Route||(null)||Please refer to the log file for details about 1 Info(s)||lly_SD1_placeroute_log.rpt;liberoaction://open_report/file/lly_SD1_placeroute_log.rpt||(null);(null)
HelpInfo,D:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,D:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
